### ISSUE TITLE
incorrect prereqs

### ISSUE THREAD

**Issue by karenetheridge** [mperry2/Config-INI-Reader-Encrypted#1]
Hi, I'm opening an issue here because the RT queue isn't yet created. sorry about that.

You inherit from Config::INI::Reader, but that's not declared as a prereq.

In addition, I see you're using File::Slurp... please please please avoid that module, it is horribly broken. This article describes some good alternatives (I like Path::Tiny, but IO::All is also popular) -- http://shadow.cat/blog/matt-s-trout/mstpan-5/

**Comment by mperry2** [comment]
Thanks for the feedback, Karen. PAUSE won't let me upload the fix, so I'll put it on my web site next week and update this repo then.

**Comment by mperry2** [comment]
Here's the location of the fixed module: http://www.cpan.org/modules/by-authors/id/M/MP/MPERRY/Config-INI-Reader-Encrypted-0.01.zip
